          FUNCTION PHITHH(ARGUM2)
C
C
C       THIS SUBROUTINE IS USED BY V076 AND V073 ONLY
C
C
C PURPOSE : PROGRAM CALCULATES THE FOURIER TRANSFORM OF THE CORRELATION
C           FUNCTION IN THE AZIMUTHAL DIRECTION AS A FUNCTION OF
C           NON-DIMENSIONAL FREQUENCY
C
C METHOD : 12/14/79 VERSION USES GAUSSIAN AUTOCORRELATION FUNCTION.
C          FORM FOLLOWS EQUATION 27 IN W.D. MARK'S "ROTOR INLET
C          TURBULENCE" PAGE 10.
C
        IMPLICIT REAL*8 (A - H , O - Z )
          DATA PI/3.14159/
C
C  NEED SWITCH TO AVOID UNDERFLOW ON EXPONENTIATION.  RANGE
C  IS E+-38.
C
          A=ARGUM2**2
          B=A/PI
          IF(B.GT.87.) GO TO 10
          C=2.*DEXP(-B)
          GO TO 20
 10        C=0.0D+00
 20       CONTINUE
          PHITHH=C
             RETURN
             END
