            FUNCTION PHIXHT(ARGUM1)
C
C       THIS SUBROUTINE IS USED BY V076 AND V073 ONLY
C
C
C  PURPOSE : PROGRAM CALCULATES THE FOURIER TRANSFORM OF THE CORRELATION
C            FUNCTION IN THE AXIAL DIRECTION AS A FUNCTION OF
C            NONDIMENSIONAL FREQUENCY
C
C
C METHOD : 12/14/79 VERSION USES GAUSSIAN AUTOCORRELATION FUNCTION.
C          FORM FOLLOWS EQUATION 27 IN W.D. MARK'S "ROTOR INLET
C          TURBULENCE" PAGE 10.
C
C
C
C  NEED SWITCH TO AVOID UNDERFLOW ON EXPONENTIATION.  RANGE
C  IS E+-38
C
        IMPLICIT REAL*8 (A - H , O - Z )
          DATA PI/3.14159/
         A=ARGUM1**2
          B=A/PI
          IF(B.GT.87.) GO TO 10
          C=2.*DEXP(-B)
          GO TO 20
 10       C=0.0D+00
 20       CONTINUE
          PHIXHT=C
        RETURN
        END
