        SUBROUTINE RMODE(MM,X,AMN,BMN,PSI,IERROR)
C       THIS SUBROUTINE IS USED BY V071 - V076
C
C SOFTWARE ID : V070
C
C
C AUTHOR :    UNKNOWN
C
C DATE : UNKNOWN
C
C
C DATED REVISIONS :
C
C  11/17/87 S. L. SKILES ADDED ERROR CHECK FOR Y BESSEL FUNCTION SET TO
C           - INFINITY IN THE CALCULATION OF THE RADIAL MODE SHAPE (PSI)
C           BY CALLING ERRMSG(15) WHEN IERPSI(2) = 3
C
C
C  04/01/91 B. E. PRUITT CHANGED PROGRAM TO ACCEPT BESSEL FUNCTIONS AND
C           THEIR DERIVATIVES FROM THE BESJ AND BESY SUBROUTINES.
C
C
C  08/15/91 B.E. PRUITT PLACED IER=3 ERROR IN THIS ROUTINE.
C          
C$
C -------------------------------------------------------------------
C
C PURPOSE : CALCULATE RADIAL MODE SHAPE PSI FOR THE (M,N) RADIAL MODE OF
C           AN ANNULAR DUCT
C
C
C FORM OF CALL:
C       CALL RMODE(MM,X,AMN,BMN,PSI,IERROR)
C
C
C ARGUMENT LIST  :
C MM - CIRCUMFERENTIAL MODE NUMBER (INPUT)
C X - XMN * (RADIUS/TIP RADIUS) (INPUT)
C AMN AND BMN - WEIGHTING FACTORS FOR RADIAL MODE SHAPE (INPUT)
C PSI - RADIAL MODE SHAPE (OUTPUT)
C IERROR - BESSEL FUNCTION ERRORS (OUTPUT)
C
C
C INPUT: UNKNOWN
C
C
C OUTPUT: UNKNOWN
C
C
C METHOD : REFER TO EQUATIONS 4 IN C.S. VENTRES,ET AL.,
C          "TURBOFAN NOISE GENERATION", NASA-CR-167951,JULY 1982
C
C
C IDIOSYNCRASIES : UNKNOWN
C
C
C -------------------------------------------------------------------
C$
C**********************************************************************
C
C
        IMPLICIT REAL*8 (A - H , O - Z )
        DIMENSION IERROR(2)
        INTEGER MM
        IF(X.EQ.0.0D+00) GO TO 300
        FACTOR=1.0D+00
        M=MM
        IF(M.LT.0) GO TO 100
200     CONTINUE
        CALL BESJ (X,M,BJ,DUM,'RMODE ',IERROR(1))
        CALL BESY (X,M,BY,DUM,'RMODE ',IERROR(2))
C
        IF (IERROR(2) .EQ. 3)WRITE(3,400)M
 400  FORMAT(1X,//,
     &25X,'* *  N  O  T  E  :  * *',///,
     &12X,'Y BESSEL FUNCTION SET TO MINUS MACHINE INFINITY WHILE',//,
     &12X,'CALCULATING THE RADIAL MODE SHAPE, PSI, FOR "M ='I4,//)
C 
        PSI=FACTOR*(AMN*BJ+BMN*BY)
        RETURN
100     M=-M
        K=M/2
        IF((1.*M)/(2.).GT.(1.*K)) FACTOR=-1.0D+00
        GO TO 200
300     CONTINUE
        PSI=AMN
        IERROR(1)=0
        IERROR(2)=0
        print*,PSI
        RETURN
        END
