MODULE MPI_ALLREDUCEInt4Call

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_ALLREDUCE call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLREDUCEInt4

CONTAINS

  SUBROUTINE MPIALLREDUCEInt4(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                                 COMM, IERROR)
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: COUNT
    INTEGER, INTENT(IN)  :: DATATYPE
    INTEGER, INTENT(IN)  :: OPER
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLREDUCE(SENDBUF(1), RECVBUF(1), COUNT, DATATYPE, OPER, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLREDUCEInt4

END MODULE MPI_ALLREDUCEInt4Call

MODULE MPI_ALLREDUCEInt4Module
  USE MPI_ALLREDUCEInt4Call
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_ALLREDUCE
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_ALLREDUCE

  INTERFACE HTMPI_ALLREDUCE
    MODULE PROCEDURE MPI_ALLREDUCEInt4
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLREDUCEInt4(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                                  COMM, IERROR)
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: COUNT
    INTEGER, INTENT(IN)  :: DATATYPE
    INTEGER, INTENT(IN)  :: OPER
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLREDUCEInt4(SENDBUF   = SENDBUF,   &
                             RECVBUF   = RECVBUF,   &
                             COUNT     = COUNT,     &
                             DATATYPE  = DATATYPE,  &
                             OPER      = OPER,      &
                             COMM      = COMM,      &
                             IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLREDUCEInt4

END MODULE MPI_ALLREDUCEInt4Module
