MODULE MPI_GATHERInt8Call

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_GATHER call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIGATHERInt8

INTERFACE MPIGATHERInt8
  MODULE PROCEDURE MPIGATHERInt81
  MODULE PROCEDURE MPIGATHERInt82
END INTERFACE 

CONTAINS

  SUBROUTINE MPIGATHERInt81(SENDBUF, SENDCOUNT, SENDTYPE, &
                               RECVBUF, RECVCOUNT, RECVTYPE, &
                               ROOT, COMM, IERROR)
    INTEGER(KIND=int8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int8Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_GATHER(SENDBUF(1), SENDCOUNT, SENDTYPE, &
                    RECVBUF(1), RECVCOUNT, RECVTYPE, &
                    ROOT, COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIGATHERInt81

  SUBROUTINE MPIGATHERInt82(SENDBUF, SENDCOUNT, SENDTYPE, &
                               RECVBUF, RECVCOUNT, RECVTYPE, &
                               ROOT, COMM, IERROR)
    INTEGER(KIND=int8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int8Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_GATHER(SENDBUF(1),   SENDCOUNT, SENDTYPE, &
                    RECVBUF(1,1), RECVCOUNT, RECVTYPE, &
                    ROOT, COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIGATHERInt82

END MODULE MPI_GATHERInt8Call

MODULE MPI_GATHERInt8Module
  USE MPI_GATHERInt8Call
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_GATHER
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_GATHER

  INTERFACE HTMPI_GATHER
    MODULE PROCEDURE MPI_GATHERInt81
    MODULE PROCEDURE MPI_GATHERInt82
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_GATHERInt81(SENDBUF, SENDCOUNT, SENDTYPE, &
                                RECVBUF, RECVCOUNT, RECVTYPE, &
                                ROOT, COMM, IERROR)
    INTEGER(KIND=int8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int8Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIGATHERInt8(SENDBUF   = SENDBUF,   &
                          SENDCOUNT = SENDCOUNT, &
                          SENDTYPE  = SENDTYPE,  &
                          RECVBUF   = RECVBUF,   &
                          RECVCOUNT = RECVCOUNT, &
                          RECVTYPE  = RECVTYPE,  &
                          ROOT      = ROOT,      &
                          COMM      = COMM,      &
                          IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_GATHERInt81

  SUBROUTINE MPI_GATHERInt82(SENDBUF, SENDCOUNT, SENDTYPE, &
                                RECVBUF, RECVCOUNT, RECVTYPE, &
                                ROOT, COMM, IERROR)
    INTEGER(KIND=int8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int8Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIGATHERInt8(SENDBUF   = SENDBUF,   &
                          SENDCOUNT = SENDCOUNT, &
                          SENDTYPE  = SENDTYPE,  &
                          RECVBUF   = RECVBUF,   &
                          RECVCOUNT = RECVCOUNT, &
                          RECVTYPE  = RECVTYPE,  &
                          ROOT      = ROOT,      &
                          COMM      = COMM,      &
                          IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_GATHERInt82

END MODULE MPI_GATHERInt8Module
