MODULE MPI_GATHERReal8Call

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_GATHER call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIGATHERReal8

INTERFACE MPIGATHERReal8
  MODULE PROCEDURE MPIGATHERReal81
  MODULE PROCEDURE MPIGATHERReal82
END INTERFACE 

CONTAINS

  SUBROUTINE MPIGATHERReal81(SENDBUF, SENDCOUNT, SENDTYPE, &
                           RECVBUF, RECVCOUNT, RECVTYPE, &
                           ROOT, COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_GATHER(SENDBUF(1), SENDCOUNT, SENDTYPE, &
                    RECVBUF(1), RECVCOUNT, RECVTYPE, &
                    ROOT, COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIGATHERReal81

  SUBROUTINE MPIGATHERReal82(SENDBUF, SENDCOUNT, SENDTYPE, &
                            RECVBUF, RECVCOUNT, RECVTYPE, &
                            ROOT, COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_GATHER(SENDBUF(1),   SENDCOUNT, SENDTYPE, &
                    RECVBUF(1,1), RECVCOUNT, RECVTYPE, &
                    ROOT, COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIGATHERReal82

END MODULE MPI_GATHERReal8Call

MODULE MPI_GATHERReal8Module
  USE MPI_GATHERReal8Call
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_GATHER
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_GATHER

  INTERFACE HTMPI_GATHER
    MODULE PROCEDURE MPI_GATHERReal81
    MODULE PROCEDURE MPI_GATHERReal82
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_GATHERReal81(SENDBUF, SENDCOUNT, SENDTYPE, &
                             RECVBUF, RECVCOUNT, RECVTYPE, &
                             ROOT, COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIGATHERReal8(SENDBUF   = SENDBUF,   &
                       SENDCOUNT = SENDCOUNT, &
                       SENDTYPE  = SENDTYPE,  &
                       RECVBUF   = RECVBUF,   &
                       RECVCOUNT = RECVCOUNT, &
                       RECVTYPE  = RECVTYPE,  &
                       ROOT      = ROOT,      &
                       COMM      = COMM,      &
                       IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_GATHERReal81

  SUBROUTINE MPI_GATHERReal82(SENDBUF, SENDCOUNT, SENDTYPE, &
                             RECVBUF, RECVCOUNT, RECVTYPE, &
                             ROOT, COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: ROOT
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIGATHERReal8(SENDBUF   = SENDBUF,   &
                       SENDCOUNT = SENDCOUNT, &
                       SENDTYPE  = SENDTYPE,  &
                       RECVBUF   = RECVBUF,   &
                       RECVCOUNT = RECVCOUNT, &
                       RECVTYPE  = RECVTYPE,  &
                       ROOT      = ROOT,      &
                       COMM      = COMM,      &
                       IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_GATHERReal82

END MODULE MPI_GATHERReal8Module
