MODULE MPI_ALLGATHERReal4Call

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_ALLGATHER call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLGATHERReal4

  INTERFACE MPIALLGATHERReal4
    MODULE PROCEDURE MPIALLGATHERReal41
    MODULE PROCEDURE MPIALLGATHERReal42
  END INTERFACE

CONTAINS

  SUBROUTINE MPIALLGATHERReal41(SENDBUF, SENDCOUNT, SENDTYPE, &
                                RECVBUF, RECVCOUNT, RECVTYPE, &
                                COMM, IERROR)
    REAL(KIND=real4Kind), DIMENSION(:), INTENT(IN)  :: SENDBUF
    REAL(KIND=real4Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLGATHER(SENDBUF(1), SENDCOUNT, SENDTYPE, &
                       RECVBUF(1), RECVCOUNT, RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLGATHERReal41

  SUBROUTINE MPIALLGATHERReal42(SENDBUF, SENDCOUNT, SENDTYPE, &
                               RECVBUF, RECVCOUNT, RECVTYPE, &
                               COMM, IERROR)
    REAL(KIND=real4Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real4Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLGATHER(SENDBUF(1),   SENDCOUNT, SENDTYPE, &
                       RECVBUF(1,1), RECVCOUNT, RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLGATHERReal42

END MODULE MPI_ALLGATHERReal4Call

MODULE MPI_ALLGATHERReal4Module
  USE MPI_ALLGATHERReal4Call
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_ALLGATHER
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_ALLGATHER

  INTERFACE HTMPI_ALLGATHER
    MODULE PROCEDURE MPI_ALLGATHERReal41
    MODULE PROCEDURE MPI_ALLGATHERReal42
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLGATHERReal41(SENDBUF, SENDCOUNT, SENDTYPE, &
                                RECVBUF, RECVCOUNT, RECVTYPE, &
                                COMM, IERROR)
    REAL(KIND=real4Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real4Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLGATHERReal4(SENDBUF   = SENDBUF,   &
                           SENDCOUNT = SENDCOUNT, &
                           SENDTYPE  = SENDTYPE,  &
                           RECVBUF   = RECVBUF,   &
                           RECVCOUNT = RECVCOUNT, &
                           RECVTYPE  = RECVTYPE,  &
                           COMM      = COMM,      &
                           IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLGATHERReal41

  SUBROUTINE MPI_ALLGATHERReal42(SENDBUF, SENDCOUNT, SENDTYPE, &
                                RECVBUF, RECVCOUNT, RECVTYPE, &
                                COMM, IERROR)
    REAL(KIND=real4Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real4Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLGATHERReal4(SENDBUF   = SENDBUF,   &
                           SENDCOUNT = SENDCOUNT, &
                           SENDTYPE  = SENDTYPE,  &
                           RECVBUF   = RECVBUF,   &
                           RECVCOUNT = RECVCOUNT, &
                           RECVTYPE  = RECVTYPE,  &
                           COMM      = COMM,      &
                           IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLGATHERReal42

END MODULE MPI_ALLGATHERReal4Module
