MODULE MPI_ALLREDUCEReal8Call0D

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_ALLREDUCE call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLREDUCEReal80D

CONTAINS

  SUBROUTINE MPIALLREDUCEReal80D(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                                COMM, IERROR)
    REAL(KIND=real8Kind), INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: COUNT
    INTEGER, INTENT(IN)  :: DATATYPE
    INTEGER, INTENT(IN)  :: OPER
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLREDUCE(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLREDUCEReal80D

END MODULE MPI_ALLREDUCEReal8Call0D

MODULE MPI_ALLREDUCEReal8Module0D
  USE MPI_ALLREDUCEReal8Call0D
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_ALLREDUCE
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_ALLREDUCE

  INTERFACE HTMPI_ALLREDUCE
    MODULE PROCEDURE MPI_ALLREDUCEReal80D
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLREDUCEReal80D(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                                 COMM, IERROR)
    REAL(KIND=real8Kind), INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: COUNT
    INTEGER, INTENT(IN)  :: DATATYPE
    INTEGER, INTENT(IN)  :: OPER
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLREDUCEReal80D(SENDBUF   = SENDBUF,   &
                            RECVBUF   = RECVBUF,   &
                            COUNT     = COUNT,     &
                            DATATYPE  = DATATYPE,  &
                            OPER      = OPER,      &
                            COMM      = COMM,      &
                            IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLREDUCEReal80D

END MODULE MPI_ALLREDUCEReal8Module0D
