MODULE MPI_ALLGATHERDblePrecCall

  USE IncludeMPIImplementation

  ! this module actually makes the F77 MPI_ALLGATHER call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLGATHERDblePrec

  INTERFACE MPIALLGATHERDblePrec
    MODULE PROCEDURE MPIALLGATHERDblePrec1
    MODULE PROCEDURE MPIALLGATHERDblePrec2
  END INTERFACE

CONTAINS

  SUBROUTINE MPIALLGATHERDblePrec1(SENDBUF, SENDCOUNT, SENDTYPE, &
                                   RECVBUF, RECVCOUNT, RECVTYPE, &
                                   COMM, IERROR)
    DOUBLE PRECISION, DIMENSION(:), INTENT(IN)  :: SENDBUF
    DOUBLE PRECISION, DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLGATHER(SENDBUF, SENDCOUNT, SENDTYPE, &
                       RECVBUF, RECVCOUNT, RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLGATHERDblePrec1

  SUBROUTINE MPIALLGATHERDblePrec2(SENDBUF, SENDCOUNT, SENDTYPE, &
                                   RECVBUF, RECVCOUNT, RECVTYPE, &
                                   COMM, IERROR)
    DOUBLE PRECISION, DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    DOUBLE PRECISION, DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLGATHER(SENDBUF, SENDCOUNT, SENDTYPE, &
                       RECVBUF, RECVCOUNT, RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLGATHERDblePrec2

END MODULE MPI_ALLGATHERDblePrecCall

MODULE MPI_ALLGATHERDblePrecModule
  USE MPI_ALLGATHERDblePrecCall

  ! this module is the wrapper to make the new F95 MPI_ALLGATHER
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_ALLGATHER

  INTERFACE HTMPI_ALLGATHER
    MODULE PROCEDURE MPI_ALLGATHERDblePrec1
    MODULE PROCEDURE MPI_ALLGATHERDblePrec2
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLGATHERDblePrec1(SENDBUF, SENDCOUNT, SENDTYPE, &
                                    RECVBUF, RECVCOUNT, RECVTYPE, &
                                    COMM, IERROR)
    DOUBLE PRECISION, DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    DOUBLE PRECISION, DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLGATHERDblePrec(SENDBUF   = SENDBUF,   &
                              SENDCOUNT = SENDCOUNT, &
                              SENDTYPE  = SENDTYPE,  &
                              RECVBUF   = RECVBUF,   &
                              RECVCOUNT = RECVCOUNT, &
                              RECVTYPE  = RECVTYPE,  &
                              COMM      = COMM,      &
                              IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLGATHERDblePrec1

  SUBROUTINE MPI_ALLGATHERDblePrec2(SENDBUF, SENDCOUNT, SENDTYPE, &
                                    RECVBUF, RECVCOUNT, RECVTYPE, &
                                    COMM, IERROR)
    DOUBLE PRECISION, DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    DOUBLE PRECISION, DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLGATHERDblePrec(SENDBUF   = SENDBUF,   &
                              SENDCOUNT = SENDCOUNT, &
                              SENDTYPE  = SENDTYPE,  &
                              RECVBUF   = RECVBUF,   &
                              RECVCOUNT = RECVCOUNT, &
                              RECVTYPE  = RECVTYPE,  &
                              COMM      = COMM,      &
                              IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLGATHERDblePrec2

END MODULE MPI_ALLGATHERDblePrecModule
