MODULE MPI_ALLTOALLVReal8Call

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_ALLTOALLV call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLTOALLVReal8

  INTERFACE MPIALLTOALLVReal8
    MODULE PROCEDURE MPIALLTOALLVReal81
    MODULE PROCEDURE MPIALLTOALLVReal82
  END INTERFACE

CONTAINS

  SUBROUTINE MPIALLTOALLVReal81(SENDBUF, SENDCOUNTS, SDISPLS, SENDTYPE, &
                                RECVBUF, RECVCOUNTS, RDISPLS, RECVTYPE, &
                                COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:), INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, DIMENSION(:), INTENT(IN)  :: SDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: SENDCOUNTS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RECVCOUNTS
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM ! handle
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLTOALLV(SENDBUF(1), SENDCOUNTS(1), SDISPLS(1), SENDTYPE, &
                       RECVBUF(1), RECVCOUNTS(1), RDISPLS(1), RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLTOALLVReal81

  SUBROUTINE MPIALLTOALLVReal82(SENDBUF, SENDCOUNTS, SDISPLS, SENDTYPE, &
                                RECVBUF, RECVCOUNTS, RDISPLS, RECVTYPE, &
                                COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, DIMENSION(:), INTENT(IN)  :: SDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: SENDCOUNTS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RECVCOUNTS
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM ! handle
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLTOALLV(SENDBUF(1),   SENDCOUNTS(1), SDISPLS(1), SENDTYPE, &
                       RECVBUF(1,1), RECVCOUNTS(1), RDISPLS(1), RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLTOALLVReal82

END MODULE MPI_ALLTOALLVReal8Call

MODULE MPI_ALLTOALLVReal8Module
  USE MPI_ALLTOALLVReal8Call
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_ALLTOALLV
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_ALLTOALLV

  INTERFACE HTMPI_ALLTOALLV
    MODULE PROCEDURE MPI_ALLTOALLVReal81
    MODULE PROCEDURE MPI_ALLTOALLVReal82
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLTOALLVReal81(SENDBUF, SENDCOUNTS, SDISPLS, SENDTYPE, &
                                 RECVBUF, RECVCOUNTS, RDISPLS, RECVTYPE, &
                                 COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, DIMENSION(:), INTENT(IN)  :: SDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: SENDCOUNTS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RECVCOUNTS
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM ! handle
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLTOALLVReal8(SENDBUF    = SENDBUF,    &
                           SENDCOUNTS = SENDCOUNTS, &
                           SDISPLS    = SDISPLS,    &
                           SENDTYPE   = SENDTYPE,   &
                           RECVBUF    = RECVBUF,    &
                           RECVCOUNTS = RECVCOUNTS, &
                           RDISPLS    = RDISPLS,    &
                           RECVTYPE   = RECVTYPE,   &
                           COMM       = COMM,       &
                           IERROR     = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLTOALLVReal81

  SUBROUTINE MPI_ALLTOALLVReal82(SENDBUF, SENDCOUNTS, SDISPLS, SENDTYPE, &
                                 RECVBUF, RECVCOUNTS, RDISPLS, RECVTYPE, &
                                 COMM, IERROR)
    REAL(KIND=real8Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    REAL(KIND=real8Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, DIMENSION(:), INTENT(IN)  :: SDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: SENDCOUNTS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RDISPLS
    INTEGER, DIMENSION(:), INTENT(IN)  :: RECVCOUNTS
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM ! handle
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLTOALLVReal8(SENDBUF    = SENDBUF,    &
                           SENDCOUNTS = SENDCOUNTS, &
                           SDISPLS    = SDISPLS,    &
                           SENDTYPE   = SENDTYPE,   &
                           RECVBUF    = RECVBUF,    &
                           RECVCOUNTS = RECVCOUNTS, &
                           RDISPLS    = RDISPLS,    &
                           RECVTYPE   = RECVTYPE,   &
                           COMM       = COMM,       &
                           IERROR     = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLTOALLVReal82

END MODULE MPI_ALLTOALLVReal8Module
