MODULE MPI_ALLGATHERInt4Call

  USE IncludeMPIImplementation
  USE MPIKindDefs

  ! this module actually makes the F77 MPI_ALLGATHER call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLGATHERInt4

  INTERFACE MPIALLGATHERInt4
    MODULE PROCEDURE MPIALLGATHERInt41
    MODULE PROCEDURE MPIALLGATHERInt42
  END INTERFACE

CONTAINS

  SUBROUTINE MPIALLGATHERInt41(SENDBUF, SENDCOUNT, SENDTYPE, &
                                  RECVBUF, RECVCOUNT, RECVTYPE, &
                                  COMM, IERROR)
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLGATHER(SENDBUF(1), SENDCOUNT, SENDTYPE, &
                       RECVBUF(1), RECVCOUNT, RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLGATHERInt41

  SUBROUTINE MPIALLGATHERInt42(SENDBUF, SENDCOUNT, SENDTYPE, &
                                  RECVBUF, RECVCOUNT, RECVTYPE, &
                                  COMM, IERROR)
    INTEGER(KIND=int4Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int4Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLGATHER(SENDBUF(1),   SENDCOUNT, SENDTYPE, &
                       RECVBUF(1,1), RECVCOUNT, RECVTYPE, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLGATHERInt42

END MODULE MPI_ALLGATHERInt4Call

MODULE MPI_ALLGATHERInt4Module
  USE MPI_ALLGATHERInt4Call
  USE MPIKindDefs

  ! this module is the wrapper to make the new F95 MPI_ALLGATHER
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: HTMPI_ALLGATHER

  INTERFACE HTMPI_ALLGATHER
    MODULE PROCEDURE MPI_ALLGATHERInt41
    MODULE PROCEDURE MPI_ALLGATHERInt42
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLGATHERInt41(SENDBUF, SENDCOUNT, SENDTYPE, &
                                   RECVBUF, RECVCOUNT, RECVTYPE, &
                                   COMM, IERROR)
    INTEGER(KIND=int4Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int4Kind), DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLGATHERInt4(SENDBUF   = SENDBUF,   &
                             SENDCOUNT = SENDCOUNT, &
                             SENDTYPE  = SENDTYPE,  &
                             RECVBUF   = RECVBUF,   &
                             RECVCOUNT = RECVCOUNT, &
                             RECVTYPE  = RECVTYPE,  &
                             COMM      = COMM,      &
                             IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLGATHERInt41

  SUBROUTINE MPI_ALLGATHERInt42(SENDBUF, SENDCOUNT, SENDTYPE, &
                                   RECVBUF, RECVCOUNT, RECVTYPE, &
                                   COMM, IERROR)
    INTEGER(KIND=int4Kind), DIMENSION(:)  , INTENT(IN)  :: SENDBUF
    INTEGER(KIND=int4Kind), DIMENSION(:,:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: SENDCOUNT
    INTEGER, INTENT(IN)  :: RECVCOUNT
    INTEGER, INTENT(IN)  :: SENDTYPE
    INTEGER, INTENT(IN)  :: RECVTYPE
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLGATHERInt4(SENDBUF   = SENDBUF,   &
                             SENDCOUNT = SENDCOUNT, &
                             SENDTYPE  = SENDTYPE,  &
                             RECVBUF   = RECVBUF,   &
                             RECVCOUNT = RECVCOUNT, &
                             RECVTYPE  = RECVTYPE,  &
                             COMM      = COMM,      &
                             IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLGATHERInt42

END MODULE MPI_ALLGATHERInt4Module
