MODULE MPI_ALLREDUCERealCall

  USE IncludeMPIImplementation

  ! this module actually makes the F77 MPI_ALLREDUCE call for character data

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPIALLREDUCEReal

CONTAINS

  SUBROUTINE MPIALLREDUCEReal(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                              COMM, IERROR)
    REAL, DIMENSION(:), INTENT(IN)  :: SENDBUF
    REAL, DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: COUNT
    INTEGER, INTENT(IN)  :: DATATYPE
    INTEGER, INTENT(IN)  :: OPER
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPI_ALLREDUCE(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                       COMM, IERROR)

    IF (IERROR == MPI_SUCCESS) THEN
      IERROR = 0
    END IF

    RETURN
  END SUBROUTINE MPIALLREDUCEReal

END MODULE MPI_ALLREDUCERealCall

MODULE MPI_ALLREDUCERealModule
  USE MPI_ALLREDUCERealCall

  ! this module is the wrapper to make the new F95 MPI_ALLREDUCE
  !  call _look like_ the standard F77 call.

  IMPLICIT NONE
  PRIVATE
  PUBLIC :: MPI_ALLREDUCE

  INTERFACE MPI_ALLREDUCE
    MODULE PROCEDURE MPI_ALLREDUCEReal
  END INTERFACE

CONTAINS

  SUBROUTINE MPI_ALLREDUCEReal(SENDBUF, RECVBUF, COUNT, DATATYPE, OPER, &
                       COMM, IERROR)
    REAL, DIMENSION(:), INTENT(IN)  :: SENDBUF
    REAL, DIMENSION(:), INTENT(OUT) :: RECVBUF
    INTEGER, INTENT(IN)  :: COUNT
    INTEGER, INTENT(IN)  :: DATATYPE
    INTEGER, INTENT(IN)  :: OPER
    INTEGER, INTENT(IN)  :: COMM
    INTEGER, INTENT(OUT) :: IERROR

    CALL MPIALLREDUCEReal(SENDBUF   = SENDBUF,   &
                          RECVBUF   = RECVBUF,   &
                          COUNT     = COUNT,     &
                          DATATYPE  = DATATYPE,  &
                          OPER      = OPER,      &
                          COMM      = COMM,      &
                          IERROR    = IERROR)

    RETURN
  END SUBROUTINE MPI_ALLREDUCEReal

END MODULE MPI_ALLREDUCERealModule
